services:

  postgres:
    image: 'postgres:15.6'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: cc6240
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - cc6240


  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
      - "9142:9142"
    environment:
      - JVM_OPTS=-Xms512M -Xmx1G -XX:+UseG1GC
      - CASSANDRA_CLUSTER_NAME=CC6240
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_START_RPC=true
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - cc6240


  mongodb:
    image: 'mongodb/mongodb-community-server:6.0.9-ubi9'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data
    networks:
      - cc6240

networks:
  cc6240:
